### ISSUE TITLE
NWWW

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#309]
Runway was moved while editing

**Comment by moritzbabl** [comment]
fixed

**Comment by Czechoslovaki** [comment]
Definitely not fixed.
![image](https://user-images.githubusercontent.com/51279558/121072360-f6cadd80-c785-11eb-8cbd-263119899db4.png)
